### PR TITLE
Www plugins from packagist

### LINKED ISSUE #1124: Have docs site pull extension docs from their repo README files
The docs.wpgraphql.com site should pull the README from each extension as the content for the docs shown for that extension. This way, each extension can maintain their canonical docs in their repo and be reflected in the searchable docs site. 

Additional docs required for extensions should be maintained separately by said extension.

### PR DESCRIPTION
**Pull request by moonmeister**
Well, I had a bug to learn how to write a source plugin for Gatsby. So, first I wrote an entire [JS client](https://github.com/moonmeister/packagist-api-client) for the packagist API. Then I used that to build a [gatsby-source-packagist](https://github.com/moonmeister/gatsby-source-packagist) to allow searching packagist and integrating that with the GAtsby data layer...and now we're here...to the point we can integrate it. And I see @jasonbahl has done all this work the \*Easy?\* way in #1134... :sob: :rofl:

It looks like he was hard coding the package names, so this makes that dynamic. Plus if he already did all the front end work I don't have to :clap:

I just took a quick look Jason and it looks like you're getting the full package details while I'm just returning some really basic data ( name, description, url, repository, downloads, favers). If there is data you want here that I'm not including I can add this as feature to the Gatsby API to fetch the full details.

Finally, let me know what the best way to move forward with the front-end of this... You're welcome to commit to this PR or I'm happy to help if I have time (clearly I have over the last week :roll_eyes: )

## Related

Closes #1124 
Related to #1134

### CODE REVIEW

**Comment by jasonbahl** [comment]
@moonmeister if your PR actually works, that's great! I never merged mine because I wasn't ever able to get it working properly with the Apollo Docs Theme I'm using. 🤦‍♂️ 

I'll check out this PR here shortly. Thanks so much for doing this!!

**Comment by moonmeister** [comment]
Well right now this is just the sourre plugin integration. I hadn't gotten to front-end work.

**Comment by jasonbahl** [comment]
> If there is data you want here that I'm not including I can add this as feature to the Gatsby API to fetch the full details.

@moonmeister I originally wanted to pull the full README file of each plugin as well, that way the content would be searchable on the docs site. I think folks coming to `docs.wpgraphql.com` searching something like "custom fields" might find the metabox.io extension and the acf extension, etc because their README would include the language "custom fields", where it might not be present in the title or description.

**Comment by jasonbahl** [comment]
> Well right now this is just the sourre plugin integration. I hadn't gotten to front-end work.

Ah ya. Actually, I think the front end maybe _was_ working? I think the issue I was actually having was maybe the downloading of the README files from Github?

It's been a minute since I worked on the PR so I don't recall all the specifics right now. 

If you can get it working, that would be AMAZING. 

I'm cool with whatever works to start, and we can iterate from there.

**Comment by moonmeister** [comment]
Well the readme is included in this ( as long as it's a GitHub repo). And integrates with gatsby-transform-markdown. So if that and links are all you want all the data should be available. I'm moving back to the states in a couple days so I'll be short on time but I'll see if i can get any thing working on the front end.

**Pull request closed without merging**
