### PR TITLE
Remove redundant CI combinations

### PR DESCRIPTION
**Pull request by szepeviktor**
These are already generated by the matrix.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Very strange. Where do these come from?

kép

**Comment by jasonbahl** [comment]
Looks like this PR removes the tests altogether 🤔 

I think there's a setting in the repo that's adding the redundant settings. Checking it out 👀

**Comment by szepeviktor** [comment]
This prevented CI from starting:

https://github.com/wp-graphql/wp-graphql/blob/a355df661f119e84ff29291afdea2a0e918a697a/.github/workflows/testing-integration.yml#L8-L13

**Comment by jasonbahl** [comment]
Ah! Thanks for pointing that out. Got the other PR merged as I confirmed it ran the tests. I also updated the setting in Github to not require the tests that were not configured to run.

**Pull request closed without merging**
