### PR TITLE
Move main class to its own file

### PR DESCRIPTION
**Pull request by szepeviktor**
- [x] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [x] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!

What does this implement/fix? Explain your changes.
---------------------------------------------------
Huge main file with a class in the middle.

Does this close any currently open issues?
------------------------------------------
Nope.

Any other comments?
-------------------
🚀 This is only `cp wp-graphql.php src/WPGraphQL.php` with 1 line:

```php
$main_file_path = dirname( __DIR__ ) . '/wp-graphql.php';
```

It would be nicer to pass `__FILE__` to the constructor...

Where has this been tested?
---------------------------
Nowhere! Waiting for CI.

### CODE REVIEW

**Comment by szepeviktor** [comment]
> Coverage decreased (-0.9%)

I have nothing to do with it :)

**Comment by jasonbahl** [comment]
@szepeviktor I added a few additional changes. I like the simplification here 👏

**Comment by szepeviktor** [comment]
Okay! One of the Cest-s freaked out.

**Comment by jasonbahl** [comment]
Looks like the failing cest was an anomole. Re-ran tests and we're good.

**Pull request merged**
