### PR TITLE
Make the post date field to conform to RFC3339

### PR DESCRIPTION
**Pull request by manzoorwanijk**
`dateGmt` field already conforms to RFC3339, same should be for the `date` field.

Where has this been tested?
---------------------------
**Operating System:** Ubuntu 18.04

**WordPress Version:** 5.1.1

### CODE REVIEW

**Comment by jasonbahl** [comment]
@manzoorwanijk do you mind creating a corresponding issue for this so we can track it?

Thanks!

**Comment by manzoorwanijk** [comment]
Created #822

**Comment by jasonbahl** [comment]
@manzoorwanijk Thanks!

**Comment by jasonbahl** [comment]
Ok, so this breaks several tests. . .but it's a good breaking change. . .we'll just need to update the tests and document the breaking change during release.

**Comment by jasonbahl** [comment]
Closes #620

**Comment by jasonbahl** [comment]
I updated the tests to pass with this change. 😄

**Pull request merged**
