### PR TITLE
feat: introduce common interfaces (again)

### LINKED ISSUE #1738: Common Interfaces that other Interfaces can Implement
The GraphQL Spec recently added support for Interfaces implementing other Interfaces, and the GraphQL PHP implementation even more recently added support for this. 

WPGraphQL should provide some common interfaces that can be implemented by other Interfaces. 

## Example

All connections in the graph currently return edges and nodes. The Type of Edge and Type of Node vary, but this is common to all connections, so we can provide a common `Connection` Interface.

```graphql
Interface Connection {
  edges: [ ConnectionEdge ]
  nodes: [ node ]
}
```

Then, we can add slightly more specific Interfaces. For example, all connections that connect _to_ Post objects (of any post type) are connections to `ContentNodes`, so we can have an Interface like so: 

```graphql
Interface ContentNodeConnection implements Connection {
  edges: [ ContentNodeConnectionEdge ]
  nodes: [ ContentNode ]
}
```

Then, connections to a specific Post Type could implement a more specific Connection: 

```graphql
Interface PostConnection implements ContentNodeConnection {
  edges: [ PostConnectionEdge ]
  nodes: [ Post ]
}
```

Then, we can have additional general interfaces such as: 

```graphql
Interface TermObjectToContentNodeConnection implements ContentNodeConnection {
  edges: [ ContentNodeConnectionEdge ]
  nodes: [ ContentNode ]
}
```

And then a specific implementation: 

```graphql
Type TagToPostConnectionEdge implements TermObjectToContentNodeConnection {
  edges: [ TagToPostConnectionEdge ]
  nodes: [ Post ]
}
```

## Added Value

This adds value to both client and server developers by providing more clarity via Introspection and more specific ways to customize the Schema on the server. 

### Introspection

Currently it's difficult to determine all the connections in the graph, but if all connections implemented a common `Connection` interface, Introspection could enable consumers to easily know about _all_ Connections by querying for all Types in the Schema that implement the Connection interface. 

Currently, trying to find all connections via introspection is, well, interesting: 

Screen Shot 2021-02-26 at 11 52 52 AM

### Server Customization

Having Broad and Specific Interfaces and Types will allow server developers extending the Schema and underlying behavior more precise control over how to hook into the Graph. 

For example, let's say I wanted to add a custom filter too _all_ connections. Perhaps something like page-based pagination arguments. 

I could apply that to the `Connection` Interface, and _all_ connections in the graph would then have these fields. 

Or, if I wanted to add some edge data to _all_ `TermObjectToContentNode` connections, I could target that Interface, or more precisely target the `TagToPostObjectConnection` to add edge data to just `Tag->Post` connections.

### PR DESCRIPTION
**Pull request by jasonbahl**
What does this implement/fix? Explain your changes.
---------------------------------------------------

This introduces common interfaces. This PR is a fresh take on #2022 

Interfaces introduced in this PR are: 

- [x] Connection
- [x] ConnectionEdge
- [x] Edge
- [x] OneToOneConnection
- [x] ContentNodeConnection
- [x] ContentTypeConnection
- [x] CommentConnection
- [x] CommenterConnection
- [x] ContentNodeConnection
- [x] HierarchicalNode
- [x] MenuConnection
- [x] MenuItemConnection
- [x] MenuItemLinkableConnection
- [x] Previewable
- [x] TaxonomyConnection
- [x] TermNodeConnection
- [x] UserConnection

Does this close any currently open issues?
------------------------------------------
closes #1738 

Any other comments?
-------------------
These connections add a lot of value to Schema organization, code reusability, and introspection. 

One can now use GraphiQL to find all instances of Connections in the Schema like so: 

connection-interface-implementations

One could also look for all Connections that implement a more specific Connection Interface, such as `ContentNodeConnection`. This interface is applied to any node that has a connection to any type of Content Node. So a User to Post connection is a `ContentNodeConnection` and a User to Page connection is also a ContentNodeConnection. 

content-node-connection-implementations

These shared connection interfaces allow client developers to have a better understanding of shared properties of connections and can allow for reduced code when querying similar data from the Graph. 

On the server side, developers can more easily add features to specific connections or general connection interfaces.

### CODE REVIEW

**Comment by justlevine** [comment]
Really cool stuff. Do we want to keep the old (admittedly poorly-named) `ContentRevisionUnion` instead of `ContentRevision` for back-compat?

**Comment by jasonbahl** [comment]
> Really cool stuff. Do we want to keep the old (admittedly poorly-named) ContentRevisionUnion instead of ContentRevision for back-compat?

Ya, perhaps we keep the `ContentRevisionUnion` Type, and deprecate the `revisions` connections that resolve to it, then introduce a new field with a new name that resolves as a `ContentNode` connection. . .then remove the deprecated type and field later.

Thoughts on a new name for the field? 

```
post.revisions @deprecated
post.contentRevisions?
```

**Comment by jasonbahl** [comment]
There's only 2 places the `ContentRevisionUnion` was referenced: 

```
RootQuery.revisions
User.revisions
```

I'm thinking we can deprecate these and introduce: 

```
RootQuery.revisedNodes
User.revisedNodes
```
```

**Comment by justlevine** [comment]
Not sure about `revisedNodes`, since semantically it implies nodes that have been revised and not individual `revision` snapshots of the particular node... Idk naming things is hard 😵‍💫

**Comment by jasonbahl** [comment]
@justlevine ah! I remember why I had to make this change. 

With the introduction of the `Connection` and `Edge` interfaces applied to all connections, we get errors like this now: 

```
Interface field Connection.nodes expects type [Node!]! but UserToRevisionsConnection.nodes is type [ContentRevisionUnion!]!.
```

I think the best way forward is to make this "technically" breaking change. 

For most use (99%+?) cases, it won't actually be a breaking change. 

Because the previous connection returned a Union instead of an Interface, the only way to query was like so (using the `...on` syntax for every single type)

```
{
  viewer {
    revisions {
      nodes {
        __typename
        ... on Post {
          id
          uri
          isRevision
        }
        ... on Page {
          id
          uri
          isRevision
        }
      }
    }
  }
  revisions {
    nodes {
      __typename
      ... on Post {
        id
        uri
        isRevision
      }
      ... on Page {
        id
        uri
        isRevision
      }
    }
  }
}
```

Since the new connection is an Interface, the same queries will still work. 

### v1.12.2
Here's the same query on WPGraphQL v1.12.2 (ContentRevisionUnion)

CleanShot 2022-11-23 at 14 23 46


### Current PR
And here's the same query with the changes from this PR applied

CleanShot 2022-11-23 at 14 22 23@2x

----

The only way it would cause a break would be if someone were querying like so: 

```graphql
{
  viewer {
    revisions {
      ... on UserToContentRevisionUnionConnection {
        nodes {
          __typename
          ... on Post {
            id
            uri
            isRevision
          }
          ... on Page {
            id
            uri
            isRevision
          }
        }
      }
    }
  }
  revisions {
    ... on RootQueryToContentRevisionUnionConnection {
      nodes {
        __typename
        ... on Post {
          id
          uri
          isRevision
        }
        ... on Page {
          id
          uri
          isRevision
        }
      }
    }
  }
}
```

Which seems highly unlikely, but something we can call out in the release notes.

**Comment by jasonbahl** [comment]
fwiw, working on this makes me want to re-visit https://github.com/wp-graphql/wp-graphql/pull/2355. I still don't quite now how to resolve that "problem" but it keeps haunting me. 

I have several one-off utility post types that I don't want to be lumped together as "content" but they keep showing up in my `contentNodes { ... }` queries. lol

**Comment by jasonbahl** [comment]
@justlevine we could potentially add something to the connection config for exluding the `Connection` and `Edge` interfaces too 🤔 

like:

```php
register_graphql_connection( [
  'fromType' => 'RootQuery',
  'toType'               => 'ContentRevisionUnion',
  ...
  'exclude_interfaces' => [ 'Connection' ],
  'exclude_edge_interfces' => [ 'Edge' ],
] );
```

🤔

**Pull request merged**
