### PR TITLE
Setup post data just before executing resolver functions 

### LINKED ISSUE #905: Cannot query hierarchical taxonomy children while querying the connected post type too
Steps to reproduce 

Add following taxonomy

```php
add_action('init', function() {
	register_taxonomy('test', 'page', [
		'hierarchical' => true,
		'label' => __( 'Test' ),
		'show_ui' => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'test',
		'graphql_plural_name' => 'tests'
	] );
});
```

Create parent and child terms

image

You should be able to query the child:

image

But convert the query to 

```graphql
{
  tests {
    nodes {
      children {
        nodes {
          name
        }
      }
    }
  }
  pages {
    nodes {
      title
    }
  }
}
```

And the result from term children disappears:

image

If unrelated post type is queried the children query works again:

image

I'm using the current `develop`(0d4409fc942788ca090e050e60cf12a2e244562c) branch from wp-graphql without other plugins

### PR DESCRIPTION
**Pull request by epeli**
Fixes #905 and probably #887

### CODE REVIEW

**Comment by epeli** [comment]
Here's potential fix for this test https://github.com/wp-graphql/wp-graphql/commit/26ea392d5830299b1b951c0198fb6a88278ff4e7

**Comment by epeli** [comment]
Oh,  it is now possible to resolve conflicts from the browser 😮

**Comment by jasonbahl** [comment]
> Oh, it is now possible to resolve conflicts from the browser 😮

I think it's been possible for a while now 🤔 . . . but I believe we've seen it cause issues in the past on some codebases. 

Gotta proceed with caution sometimes.

**Comment by epeli** [comment]
Well you cannot test your code without without committing so I wouldn't use it anything but the simplest things.

**Pull request merged**
