### PR TITLE
Fix typos [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by szepeviktor**
### This is a bug report, not a PR

Found some misspellings.

I let you add more commits.
This is not a PR just a bug report 🐛

### CODE REVIEW

**Comment by szepeviktor** [comment]
`setisQueryComposerOpen` could be `setIsQueryComposerOpen`

**Comment by justlevine** [comment]
This is amazing @szepeviktor I really love your eye for detail!. I'll start parceling these off into commits/prs as soon as I can 🥰

**Comment by szepeviktor** [comment]
You may be interested in the "Integrity" workflow, it cares about bytes.
https://github.com/szepeviktor/byte-level-care/blob/master/.github/workflows/reusable-integrity.yml#L3-L4
([this is](https://github.com/szepeviktor/byte-level-care/blob/master/.github/workflows/integrity.yml#L22) how to call it)

**Comment by justlevine** [comment]
All changes have been cherrypicked into #2498, #2499, and #2450. Closing.

**Pull request closed without merging**
