### PR TITLE
#638 add two new post type specific filters

### PR DESCRIPTION
**Pull request by hsimah**
- [x] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [x] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!

What does this implement/fix? Explain your changes.
---------------------------------------------------
Allows users to customise the `typeBy` query input and resolution.

Does this close any currently open issues?
------------------------------------------
#638 

Any other comments?
-------------------
Hello again

Where has this been tested?
---------------------------
**Operating System:** Windows 10, Red Hat

**WordPress Version:** 5.0.2

### CODE REVIEW

**Comment by jasonbahl** [comment]
Currently, filters technically exist already for this, although not as elegant as they could be. 

For example, you can currently filter in postBy args like so:

add_filter( 'graphql_RootQuery_fields', function( $fields ) {

  if ( isset( $fields['postBy'] ) {
    $args = ! empty( $fields['postBy']['args'] ? $fields['postBy']['args'] : [];
    $args['myNewArg'] = [
       'type' => 'String',
       'description' => __( 'Description of myNewArg', 'your-textdomain' ),
    ];
  }

} );

Then you can filter the args for the resolver like so: 

```
add_action( 'graphql_resovle_field', function( $result, $source, $args, $context, $info, $type_name, $field_key, $field, $field_resolver ) {

  // If the arg is set, do something with it and return the custom results
  if ( 'postBy' === $field_key && ! empty( $args['myNewArg'] ) {
    $result = do_something_with_your_new_arg( $source, $args['myNewArg'] );
  }

  return $result;

}, 10, 9 );
```

---------

I do think the filters you're adding make it more explicit that you can filter that particular entry point, but I think I'd prefer to solve this more centrally. . .possibly via introducing something like a `register_graphql_arg` function. 

I'm thinking we could probably have something like: `register_graphql_connection_arg`, `register_graphql_mutation_arg`, register_graphql_input_arg` (maybe others)

And then you could configure both the fields that should apply to the arg _AND_ what should be done with the arg's value during execution.

Something like: 

```
register_graphql_connection_arg( [
  'connectionName' => 'RootQueryToPostConnection',
  'field' => [
    'type' => 'string',
    'description' => 'description of the arg',
  ],
  'handleInput' => function( $arg ) {
     do_something_with_arg( $arg );
  }
] );
```

Totally pseudo code, but I'm thinking some entry point like this could do the heavy lifting of filtering the Schema to add the field to the Schema, but also filter the execution to add the `handleInput` (or whatever we should call it) do run during execution if the arg is present in the query/mutation. 

Need to think about it a bit more, but something along that line would be my ideal approach.

**Comment by hsimah** [comment]
@jasonbahl I didn't know about the `graphql_resolve_field` filter - that was the main reason for doing this enhancement. Given the functionality exists, I will change my filters and close this PR.

I do like your idea of having a central way to extend queries. I would offer to help but I am swamped at the moment.

**Comment by jasonbahl** [comment]
@hsimah one thing to be aware of though, is that the current `graphql_resolve_field` still executes the original resolve function. 

We probably should introduce a filter here that allows you to override the resolver without the default resolver executing. 

See: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Utils/InstrumentSchema.php#L126-L149

**Comment by hsimah** [comment]
I'm looking at that now.

If the RootQuery resolver doesn't resolve an object it throws a UserError. I'll admit I don't know a lot about PHP exceptions, but wouldn't that then not return to InstrumentSchema to fire off the filter?

**Pull request closed without merging**
