### PR TITLE
(bugfix): Fix console warnings in WPGraphiQL related to missing keys

### LINKED ISSUE #2352: WPGraphiQL Warning: Each child in a list should have a unique "key" prop.
## Issue
WPGraphiQL throws the following console logs: `Warning: Each child in a list should have a unique "key" prop.`.

See: https://wp-graphql.slack.com/archives/C3NM1M291/p1649359486552519

The first two are from the `<Button />` in AddOperations.js and the `<AuthSwitch />` in `graphiql-auth-switch.js`, but there is another one I can't figure out.

## To reproduce.
1. Install WPGraphQL
2. Open the developer console.

## Tested on:
- Wordpress: 5.9.3
- WPGraphQ: 1.8.0 (both from wpackagist and this repo).
- Ubuntu 20.04 (wsl2 + devilbox + php 8.0.15)
- Chrome: 100.0.4896.127 

### When reporting a _bug_, please be sure to include the following:
- [x] A descriptive title
- [x] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [x] What version of `WPGraphQL` you're using, and the platform(s) you're running it on
- [x] What other plugins you're using
- [x] The behavior you expect to see, and the actual behavior

### PR DESCRIPTION
**Pull request by jasonbahl**
What does this implement/fix? Explain your changes.
---------------------------------------------------
This fixes some console warnings related to WPGraphiQL

- update yarn deps
- add key to auth switch component
- add key to fullscreen toggle component
- add key to AddOperation buttons

Does this close any currently open issues?
------------------------------------------
closes #2352

### CODE REVIEW

**Comment by justlevine** [comment]
Still getting warnings. I ran `npm start` to see what components are actually throwing the warnings:

image

image

**Comment by justlevine** [comment]
Looks like `<ExplorerContext.Consumer />` solves the one on GraphQLToolbar, but leaves this:

image

**Comment by jasonbahl** [comment]
@justlevine did you run `npm install` to get the latest dependencies installed? 🤔 

I'm not seeing these console warnings anymore 🤔  (I just see the message about styled-components, but that's for another time)

CleanShot 2022-04-28 at 15 28 09

**Comment by jasonbahl** [comment]
I think I see why these warnings were being output, but I'm curious why I'm not seeing them 🤔 

I pushed up another change adding keys to the QueryComposer and Explorer components

**Review by justlevine — APPROVED** [review]
Warnings are gone 🚀

image

**Pull request merged**
