### PR TITLE
feat: add pageInfo field to connection type

### LINKED ISSUE #2648: pageInfo field should be exposed on the `Connection` Interface
### What problem does this address?

The recent addition of the `Connection` Interface adds the `edges` and `nodes` fields to the `Connection` interface, but the `pageInfo` field was not included. 

The `pageInfo` field should be included in the `Connection` interface so we can do queries like so: 

```graphql
{
  contentNodes {
    ...PaginatedConnection
  }
  terms {
    ...PaginatedConnection
  }
  users {
    ...PaginatedConnection
  }
  mediaItems {
    ...PaginatedConnection
  }
}

fragment PaginatedConnection on Connection {
  __typename
  pageInfo {
    startCursor
    endCursor
    hasNextPage
    hasPreviousPage
  }
  nodes {
    __typename
    id
  }
}
```

### What is your proposed solution?

Add `pageInfo` to the `Connection` interface type

### What alternatives have you considered?

Not adding it?

### Additional Context

I believe this will greatly improve DX for users as they will be able to more easily re-use fragments for common problems, such as pagination

### PR DESCRIPTION
**Pull request by jasonbahl**
What does this implement/fix? Explain your changes.
---------------------------------------------------
This adds the `pageInfo` field to the `Connection` interface

**FAILING TEST:** https://github.com/wp-graphql/wp-graphql/actions/runs/3597227788/jobs/6058764653#step:7:756
**PASSING TEST:** https://github.com/wp-graphql/wp-graphql/actions/runs/3597600683/jobs/6059509364#step:7:753

Does this close any currently open issues?
------------------------------------------
closes #2648 

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------

Currently each connection needs to manually request pageInfo fields. By adding the `pageInfo` field to the `Connection` interface, clients can now re-use a `pageInfo` fragment. 

**BEFORE**

```graphql
{
  contentNodes {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    nodes {
      __typename
      id
    }
  }
  terms {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    nodes {
      __typename
      id
    }
  }
  users {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    nodes {
      __typename
      id
    }
  }
  mediaItems {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    nodes {
      __typename
      id
    }
  }
  comments {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    nodes {
      __typename
      id
    }
  }
  contentTypes {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    nodes {
      __typename
      id
    }
  }
  plugins {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    nodes {
      __typename
      id
    }
  }
  themes {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    nodes {
      __typename
      id
    }
  }
  menus {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    nodes {
      __typename
      id
    }
  }
  menuItems {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    nodes {
      __typename
      id
    }
  }
}
```

**AFTER**

Now we can re-use a fragment that asks for PageInfo on _any_ connection:

```graphql
{
  contentNodes {
    ...PageInfo
  }
  terms {
    ...PageInfo
  }
  users {
    ...PageInfo
  }
  mediaItems {
    ...PageInfo
  }
  comments {
    ...PageInfo
  }
  contentTypes {
    ...PageInfo
  }
  plugins {
    ...PageInfo
  }
  themes {
    ...PageInfo
  }
  menus {
    ...PageInfo
  }
  menuItems {
    ...PageInfo
  }
}

fragment PageInfo on Connection {
  pageInfo {
    hasNextPage
    hasPreviousPage
    startCursor
    endCursor
  }
  nodes {
    __typename
    id
  }
}
```

Any other comments?
-------------------
**NOTE**: just because you _can_ query all these connections in one query, doesn't mean you should. If you really needed _all_ this data, I'd still recommend querying separately. The point, though, is that you can re-use fragments across the queries much more easily.

### CODE REVIEW

**Comment by justlevine** [comment]
I think we can dry this out with a `public static function get_fields() : array {}` in the  `PageInfo` class

**Comment by xoref** [comment]
We're using custom PageInfo fields, but this no longer works after this update as these custom fields now need to be registered? Is there any way to overrule that `::get_fields()` method and add in our custom fields? A filter would have been nice.

**Comment by justlevine** [comment]
Hey @xoref . As before, you should still be able to use `register_graphql_fields()` to add fields to an interface, the difference here being that you can now additionally target specific `{ConnectionType}PageInfo` interfaces.

How were you previously registering your `PageInfo` fields? I believe this change was additive and backwards-compatible, but perhaps there's a regression somewhere...

**Comment by xoref** [comment]
@justlevine Thanks for the quick reply. Our implementation was following [this example from your docs](https://www.wpgraphql.com/filters/graphql_connection_page_info), which worked fine until this change. Good to know that the custom fields now have to be registered, which makes sense but wasn't clear to us.

**Comment by justlevine** [comment]
@xoref I don't believe that filter was changed this release, it just now works on an interface level instead of the object level. 
Its purpose is to provide _data_ to the PageInfo type used to resolve the fields, but as noted in the example on the link you shared "You would want to register a “total” field to the PageInfo type, _then_ [emphasis added] filter the pageInfo to return the total for the query".

**Comment by xoref** [comment]
Just pointing out that this registration of the field was not needed prior to the latest release.

**Comment by jasonbahl** [comment]
@xoref do you have specific steps to reproduce? If so, can you open a new issue referencing this?

**Comment by jasonbahl** [comment]
CleanShot 2023-03-10 at 10 31 37

**Comment by jasonbahl** [comment]
I updated the snippets in the documentation page. There was a few mistakes with the snippet that was there, and it was missing some information

**Pull request merged**
