### PR TITLE
only set payload clientMutationId if inputed

### PR DESCRIPTION
**Pull request by oskarmodig**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Prevents PHP notices described in issue. 

Does this close any currently open issues?
------------------------------------------
Fixes issue #2176 PHP Notice for missing clientMutationId

### CODE REVIEW

**Comment by jasonbahl** [comment]
@oskarmodig thanks for the PR!

**Comment by jasonbahl** [comment]
@oskarmodig looks like there's some minor formatting issues. Would you mind fixing those? 

You should be able to run `composer install` then `composer run fix-cs`, then commit the re-formatted file and push it back up. 

Thanks! 🙏🏻

**Comment by jasonbahl** [comment]
Thanks for the follow-up @oskarmodig! Appreciate it! 🙌🏻

**Comment by oskarmodig** [comment]
> Thanks for the follow-up @oskarmodig! Appreciate it! 🙌🏻

@jasonbahl Thank _you_!

**Pull request merged**
