### PR TITLE
Feature/lint staged phpcs

### PR DESCRIPTION
**Pull request by TylerBarnes**
### Your checklist for this pull request
Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.

🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [x] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!

What does this implement/fix? Explain your changes.
---------------------------------------------------
This PR adds lint-staged and husky to help with keeping the codebase clean during development.
Anytime someone tries to make a commit, husky will run it's precommit git hook which calls lint-staged to run a command against the staged files. I've configured it to run phpcs and it will output any errors and bail the commit if there are any.

This doesn't force anyone to lint though as you need to run `npm install` in the project before this takes effect, so it's more of a useful tool than a guard. As you can see from this GIF, I only added one error to the file I'm testing with but `phpcs` returns 16 errors and 1 warning. So this is really useful to have going forward!

lint-staged-php-2

### CODE REVIEW

**Comment by TylerBarnes** [comment]
Oh, I nearly forgot. I actually had to delete the composer.lock in order to run composer install and get phpcs running for me. I'm not sure if that's going to cause any issues. Any ideas on that @jasonbahl ? It was having trouble resolving packages due to some conflict.

**Comment by jasonbahl** [comment]
@TylerBarnes try with `composer install --no-dev` as it looks like it's trying to add the dev dependencies for versioning, which we don't want

**Comment by jasonbahl** [comment]
when running dev scripts, you _do_ need the dev dependencies, but we don't want to ship them in the versioned code as they're not intended for execution by anything other than Travis-CI or devs running the dev scripts locally. 

To run the dev scripts, you can run `composer install` then run the script(s) you need to, then when committing for a PR, run `composer install --no-dev`

That _should_ probably be automated in some way though. . .or even better, we should just not version _any_ of the composer dependencies at all, and let automation bundle them into the distributed packages.

**Comment by jasonbahl** [comment]
@TylerBarnes weird. Maybe a PHP version conflict? 🤔

**Comment by TylerBarnes** [comment]
@jasonbahl it was a Catalina issue!
https://stackoverflow.com/a/58300437

**Comment by TylerBarnes** [comment]
Ok, I added some additional instructions. I know this feature isn't a high priority but IMO code quality and cleanliness is super important and this should help with that!

**Pull request merged**
