### PR TITLE
feat: support deprecation reason on connections

### LINKED ISSUE #2579: deprecationReason doesn't work when registering connections
### Description

when registering a connection using `register_graphql_connection` passing `deprecationReason` doesn't deprecate any of the fields generated by registering the connection. 

### Steps to reproduce

Register a connection like so: 

```php
add_action( 'graphql_register_types', function() {

	register_graphql_connection( [
		'fromType' => 'RootQuery',
		'toType' => 'Post',
		'fromFieldName' => 'deprecatedConnection',
		'deprecationReason' => 'test...'
	] );

});
```

See that `deprecatedConnection` is not actually deprecated in the Schema: 

CleanShot 2022-10-13 at 11 52 23

### Additional context

**Expectation:**

I would expect passing `deprecationReason` to `register_graphql_connection` to show the fields as deprecated. 

Like so: 

CleanShot 2022-10-13 at 11 53 13

### WPGraphQL Version

1.12.0

### WordPress Version

6.0

### PHP Version

8.0

### Additional enviornment details

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

### PR DESCRIPTION
**Pull request by jasonbahl**
What does this implement/fix? Explain your changes.
---------------------------------------------------
This passes `deprecationReason` from `register_graphql_connection` config array through to the fields that are registered to create the connection.

Does this close any currently open issues?
------------------------------------------
closes #2579 

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------

**BEFORE**

Registering a connection with a `deprecationReason` DOES NOT deprecate the field(s) that were registered to create the connection:

CleanShot 2022-10-13 at 11 56 21

**AFTER**

Registering a connection with a `deprecationReason` deprecates the field(s) that were registered to create the connection:

CleanShot 2022-10-13 at 11 55 52

### CODE REVIEW

**Review by moonmeister — APPROVED** [review]
The actual change is good, just has lots of extras in the PR, not sure if that was intentional

**Comment by justlevine** [comment]
Yeah seems develop is out of sync with main again, but the actual commit looks good to me as well

**Review by justlevine — DISMISSED** [review]

**Comment by jasonbahl** [comment]
ya. . .I need to automate `develop` getting synced back up after a release 🤦🏻‍♂️

**Comment by jasonbahl** [comment]
closing and re-opening against the updated `develop` branch

**Comment by jasonbahl** [comment]
re-opened the PR (clean diff) here: https://github.com/wp-graphql/wp-graphql/pull/2581

**Pull request closed without merging**
