### PR TITLE
#272 - Update to use GraphQL-PHP v0.11.2

### PR DESCRIPTION
**Pull request by jasonbahl**
This updates WPGraphQL to use v0.11.2 of GraphQL-PHP.

### CODE REVIEW

**Comment by CodeProKid** [comment]
@jasonbahl - this is a bit of a beast. Do you have a changelog you can link to, for what was actually changed in this library?

**Comment by CodeProKid** [comment]
Seems like travis is barfing on some composer stuff?

**Comment by jasonbahl** [comment]
@CodeProKid fixed the composer stuff. . .it's running again and I think it _should_ be good now. 

The Upgrade instructions for GraphQL-PHP are here: https://github.com/webonyx/graphql-php/blob/master/UPGRADE.md

The Changelog is here: https://github.com/webonyx/graphql-php/blob/master/CHANGELOG.md

The primary reason I wanted to update now is because there were some adjustments to work better with DataLoader, and some other core improvements to help with some other performance boosts, such as: 

- Significantly improved parser performance
- Apollo-style query batching support via server

---- 

The biggest breaking change was how Exceptions are handled. Default exceptions are no longer returned to the client as-is, they are masked as "Internal server error", so to return an exception with the request, we needed to convert Exceptions to `UserError()` to keep our implementation from breaking backward compatibility.

So a LOT of the changes in this PR are just one-liners like: https://github.com/wp-graphql/wp-graphql/pull/275/files#diff-9961a10648c95beb5c33cfbf42ec1532L155 then corresponding updates to Unit Tests to include the addition of the "category" that errors return with them now.

We now will have a lot more granular control over how we handle errors though, which is sweet (we have an open issue #216 about how to handle errors/warnings in various ways, so this update should help with that)

**Comment by jasonbahl** [comment]
@CodeProKid merging this as I don't want it lingering for long. . .got some upcoming features that rely on some of these changes.

**Pull request merged**
