### PR TITLE
CI-5745

### PR DESCRIPTION
**Pull request by mngi-arogers**
### Your checklist for this pull request
Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.

🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ x] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [x ] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!

What does this implement/fix? Explain your changes.
---------------------------------------------------
This change allows a developer to log into a running and fully-provisioned Docker container to run tests on code changes made in the IDE. This new test-running workflow eliminates the need for developers to wait on their Docker environment to start up when they want to run tests successively.

Does this close any currently open issues?
------------------------------------------
Nope.

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
N/A

Any other comments?
-------------------
Nope.

Where has this been tested?
---------------------------
**Operating System:** Linux

**WordPress Version:** 4.9.8

### CODE REVIEW

**Comment by jasonbahl** [comment]
@mngi-arogers I'm checking this out locally right now 😄

**Comment by jasonbahl** [comment]
@mngi-arogers this looks good. 

I ran through your instructions and things are much faster to re-run tests now. So when actively developing it will be much faster to work on features and make sure tests still pass, etc. 

The failing tests look like they're related to the release yesterday 🤦‍♂️ and not this PR. 

Thanks!

**Comment by mngi-arogers** [comment]
Wait don't merge yet. I think I need to tweak something in Travis hold on...

**Comment by jasonbahl** [comment]
^ just saw this. My b.

**Pull request merged**
