### PR TITLE
Feature/#223 add user registration mutation

### PR DESCRIPTION
**Pull request by kellenmace**
### Your checklist for this pull request
Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.

🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [x] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!

What does this implement/fix? Explain your changes.
---------------------------------------------------
This adds a mutation for registering a new user.

Does this close any currently open issues?
------------------------------------------
Yes, #223 

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
Here is a gif demonstrating the new feature: https://cloudup.com/cFdVhxOlsYn

Any other comments?
-------------------
This plugin rules! Thanks for creating it! 🙌🏼

Where has this been tested?
---------------------------
**Operating System:** macOS 10.13.6

**WordPress Version:** 4.9.8

### CODE REVIEW

**Comment by jasonbahl** [comment]
Reviewing from my phone, but this looks great! 

I’ll take another look when I get to a computer and will either provide feedback or get this merged. 

Thanks for working on it!!

**Comment by kellenmace** [comment]
Cool! Sounds great @jasonbahl. Thanks 😊

**Comment by jasonbahl** [comment]
@kellenmace this looks great. Merging. Thanks for working on it!

**Comment by jasonbahl** [comment]
@kellenmace ah, I may have merged too quickly. 

I'm seeing that some fields aren't saving during the mutation. 

For example, firstName and lastName don't get saved. Attached is a screenshot showing as much.

registeruser

**Comment by jasonbahl** [comment]
@kellenmace I've got a fix coming. I'll add it to the release.

**Pull request merged**
