### PR TITLE
Make the Readme simpler to read.

### PR DESCRIPTION
**Pull request by bahiirwa**
## Background
This PR seeks to make the readme.md simpler to read. Feel free to leave any comments on the commits.

## Issues
I personally have mild dyslexia so it is hard to read. I suggest to split up the file into smaller files.

## How does this implement/fix?
- [x] Extremely long Readme.md that makes it hard to focus. Split up the file into small files like
    - [x] Make a Testing.md _**(add to documentation section in readme.md)**_
    - [x] Make a Debugging.md  _**(add to documentation section in readme.md)**_
    - [x] Make a UseDocker.md  _**(add to documentation section in readme.md)**_

Other suggestions not in this PR:
- [ ] Overview belongs to the docs website
- [ ] GraphiQL Explorer belongs to the GraphiQL repo or docs website. _**(A link to it make more sense.)**_

### CODE REVIEW

**Comment by jasonbahl** [comment]
Took a super quick glance, and I like this! 

I've been wanting to clean up the README for a long time, so I appreciate the effort here. 

I'll try and take a bit more time later today to really look at all the changes with a critical eye and give actionable feedback.

**Comment by jasonbahl** [comment]
@bahiirwa @CodeProKid submitted a similar PR moving the Github files, etc. 

If you want to continue the work he did there by re-organizing the README like you have here, that would be 👌

**Comment by bahiirwa** [comment]
> If you want to continue the work he did there by re-organizing the README like you have here, that would be 👌 

@jasonbahl would be super but I can’t find the PR. Can you link it?

**Comment by CodeProKid** [comment]
@bahiirwa it's #1249

**Comment by bahiirwa** [comment]
I did a force push to incorporate the new changes.

**Comment by jasonbahl** [comment]
@bahiirwa thanks for the changes! 🙏

**Pull request merged**
