### PR TITLE
fix: php deprecation error for dynamic properties on AppContext class

### LINKED ISSUE #2981: PHP deprecated
### Description

Hi, I’m getting this error when a GraphQL request is made. This is after updating from PHP 7.3 to PHP 8.2.

Error Level: E_DEPRECATED
Message: Creation of dynamic property WPGraphQL\AppContext::$connection_query_class is deprecated
File: /bitnami/wordpress/wp-content/plugins/wp-graphql/src/Type/WPConnectionType.php
Line: 528

This is the request: /graphql?query=query%20{%20posts(first:%2032,%20where:%20{mpid1:%20%22BBULRDSL000%22})%20{%20nodes%20{%20clientId%20databaseId%20title%20content%20featuredImage%20{%20node%20{%20id%20sourceUrl%20}%20}%20postFields%20{%20fieldGroupName%20galleries%20imageAltText%20isVideo%20matchedProducts%20{%20gbLink%20gbPrice%20gbTitle%20productId%20productName%20productPrice%20productUrl%20sku%20x%20y%20}%20socialNetwork%20sourceUrl%20}%20}%20}%20}

It's a request for some posts using ACF fields.

The correct JSON is returned, but this error persists.

WordPress version 6.3.2
Plugins:
Advanced Custom Fields PRO
Forminator Pro
Really Simple SSL
WooCommerce + related plugins
WP GraphQL
WPMU Dev Dashboard

Thanks

### Steps to reproduce

Execute a query with similar structure to this: /graphql?query=query%20{%20posts(first:%2032,%20where:%20{mpid1:%20%22BBULRDSL000%22})%20{%20nodes%20{%20clientId%20databaseId%20title%20content%20featuredImage%20{%20node%20{%20id%20sourceUrl%20}%20}%20postFields%20{%20fieldGroupName%20galleries%20imageAltText%20isVideo%20matchedProducts%20{%20gbLink%20gbPrice%20gbTitle%20productId%20productName%20productPrice%20productUrl%20sku%20x%20y%20}%20socialNetwork%20sourceUrl%20}%20}%20}%20}

(using ACF fields)

### Additional context

_No response_

### WPGraphQL Version

1.18.0

### WordPress Version

6.3.2

### PHP Version

8.2

### Additional environment details

Bitnami on AWS

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

### PR DESCRIPTION
**Pull request by jasonbahl**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Sets the AppContext class to "allow dynamic properties"

Does this close any currently open issues?
------------------------------------------
closes #2981

### CODE REVIEW

**Comment by gregrickaby** [comment]
👋🏻 Hey Jason...

This can be squelched by adding the following to the list of properties in `AppContext.php`. Tested locally with PHP 8.3 and no more deprecation warnings 😄 

```php
/**
 * Stores the class to use for the connection query.
 *
 * @var WP_Query|null
 */
public $connection_query_class = null;
```

**Comment by justlevine** [comment]
> 👋🏻 Hey Jason...
> 
> This can be squelched by adding the following to the list of properties in `AppContext.php`. Tested locally with PHP 8.3 and no more deprecation warnings 😄
> 
> ```
> /**
>  * Stores the class to use for the connection query.
>  *
>  * @var WP_Query|null
>  */
> public $connection_query_class = null;
> ```

This might be a "why not both?" situation, since while `$connection_query_class` is the problem in the core, the current pattern encourages general overloading the `AbstractConnectionResolver` class with custom properties. 🤔 

Similarly (more of a note to self), while squelching the deprecation warning is our immediate concern, we do need to think about what the _ideal_ DX should be for overloading the ConnectionResolver in order to reuse an existing one instead of needing to define an entire child class (or even _if_ overloading is the way to do it vs lets say a callable in the `$config[]` ).

related:  #2821

**Comment by xbd63** [comment]
I think this is fixed, now. Thanks!

**Comment by jasonbahl** [comment]
> This might be a "why not both?" situation

@justlevine @gregrickaby ya, I agree with this (and everything @justlevine said after). 

We definitely need to shore up some patterns for hooking into AppContext. For now, I think we can do both, and then circle back in the future on what ideal patterns _should be_ if/when AppContext needs to be modified during resolution, etc

**Pull request merged**
