### PR TITLE
Neutralize Schema Linter CI workflow

### PR DESCRIPTION
**Pull request by szepeviktor**
Long-standing issue goes to sleep 🛌 

While #1342 is being worked on...

### CODE REVIEW

**Comment by szepeviktor** [comment]
Done 🍏 

Runs and fails silently.

> ✖ 441 errors detected

**Review by jasonbahl — APPROVED** [review]

**Comment by jasonbahl** [comment]
@szepeviktor thanks for working on this! 🙌

**Comment by szepeviktor** [comment]
Do you know a _junior contributor_ who will clean up the schema?

**Comment by sol-idsnake** [comment]
@szepeviktor I don't know if I qualify, but I have been looking to get my feet wet with contributions to the project for a while. Let me know if I can help.

**Comment by szepeviktor** [comment]
@sol-idsnake Your contribution is very welcome.
I suggest you to categorize those 441 schema errors and start with rare ones.
Maybe we could ignore missing description errors...

**Pull request merged**
