### PR TITLE
Upgrade `webonyx/graphql-php` to ^0.13.8

### PR DESCRIPTION
**Pull request by esamattis**
Just checking how the tests run with the latest version.

This would drop PHP 7.0 support.

### CODE REVIEW

**Comment by jasonbahl** [comment]
@esamattis can you run `composer install --no-dev` and try again? This is pulling all the dev dependencies in (things like test libs, etc)

**Comment by esamattis** [comment]
Oops. Rebased.

**Comment by esamattis** [comment]
All tests in `PostObjectConnectionQueriesTest`, `PostObjectSearchTest` fail.

Also these individual tests
✖ TermObjectQueriesTest: Term query where term does not exist (0.01s)
✖ ThemeObjectQueriesTest: Theme query where theme does not exist (0.03s)

Seem to be the same error on each so should not be too bad to fix

```
Argument 1 passed to GraphQL\Type\Definition\ResolveInfo::__construct() must be of the type string, array given, called
```

**Comment by jasonbahl** [comment]
@esamattis I made some changes to get all tests to pass, but I can't merge this PR. 

Opening a PR from my fork to merge.

**Pull request closed without merging**
