### PR TITLE
feat: add `UniformResourceIdentifiable` interface to `Comment` type

### PR DESCRIPTION
**Pull request by justlevine**
What does this implement/fix? Explain your changes.
---------------------------------------------------
This PR add the `UniformResourceIdentifiable` interface to the `Comment` object type. More specifically:

- `Comment` types now implement `UniformResourceIdentifiable`, which exposes the `uri` field.
- Added the `Comment.link` field, for parity with the [REST API](https://developer.wordpress.org/rest-api/reference/comments/#schema)
- Added support to `nodeByUri` for querying Comment URIs (`{post_link}#comment-{id}`}.

Does this close any currently open issues?
------------------------------------------

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------

Any other comments?
-------------------
`nodeByUri` does *not* validate that the `#comment-{$id}` is actually associated with the PostObject referenced in the URL for performance reasons. This means that `$uri = "/fake-post#comment-{$real-comment-id}" will resolve to the correct `Comment`.

This quirk doesnt present a security risk, and since the use case for using `nodeByUri` to get a comment is so small I think this is fine.

Where has this been tested?
---------------------------
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + php8.1.14)

**WordPress Version:** 6.4.3

### CODE REVIEW

**Comment by justlevine** [comment]
@jasonbahl I don't think these tests are failing because of me. Thoughts?

**Comment by jasonbahl** [comment]
> @jasonbahl I don't think these tests are failing because of me. Thoughts?

The GraphiQL tests are broken in general right now. @josephfusco and I are working on resolving that. I probably can remove them from the Github Workflows for now and re-instate them once we have it resolved.

**Comment by jasonbahl** [comment]
@justlevine on initial review, this is great! I'll do a more thorough review shortly. 

Love the detail and comprehensiveness of this. Totally wouldn't have expected proper support for `nodeByUri` without me having to point it out, but sure enough you covered it! Well done. 🙌🏻

**Comment by jasonbahl** [comment]
@blakewilson with this update where Comments are individually identifiable nodes, the Faust seed query could potentially be updated to support this, and Faust could "one-up" core WordPress by introducing a new concept for comment templates in the template hierarchy. 

This could be kinda cool for applications with a lot of user interaction / threads, etc 🤔 

Here's an example query getting information about the comment that could be used in the hierarchy, such as: 

comment-id -> comment-type -> comment -> index (or something to that tune)

CleanShot 2024-02-13 at 17 08 21

**Review by jasonbahl — APPROVED** [review]
well done @justlevine! 

Love the attention to detail, the support for the `nodeByUri` query, etc. 

Well done! 🙌🏻

**Pull request merged**
