### PR TITLE
Adds more strict check to "is_graphql_request()"

### PR DESCRIPTION
**Pull request by kidunot89**
### Your checklist for this pull request
Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.

🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [x] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!

What does this implement/fix? Explain your changes.
---------------------------------------------------
- Adds a more strict conditional to `Router::is_graphql_request()`.

Does this close any currently open issues?
------------------------------------------
#1021 

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Operating System:** Linux 19.2

**WordPress Version:** 5.2.3

### CODE REVIEW

**Comment by esamattis** [comment]
I don't think we'll need the "after init" check if we already have a check that works both before and after init. If we have both then we have a possibility for a bug where it returns different results before and after init.

**Comment by kidunot89** [comment]
True, but I wasn't sure if using `$_SERVER['REQUEST_URI']` was the best practice for this, so I figured it would be better to only use it when the query bars aren't available.

**Comment by jasonbahl** [comment]
Perhaps ya'll just need to check `if ( defined( 'GRAPHQL_REQUEST ) && true === GRAPHQL_REQUEST ) )`?

The Router is only used if you're using GraphQL at the `/graphql` endpoint, which isn't the case for all GraphQL requests. 

Do we need a more general `WPGraphQL::is_graphql_request()` method instead of one _just_ in the Router?

**Comment by jasonbahl** [comment]
> Perhaps ya'll just need to check if ( defined( 'GRAPHQL_REQUEST ) && true === GRAPHQL_REQUEST ) )?

I guess that's also not defined before init. 

I think more context would go a long way for me.

**Comment by kidunot89** [comment]
Just realized the conditional is invalid. I'll need to make some quick changes.

**Comment by jasonbahl** [comment]
@kidunot89 @esamattis I'll merge this. I think there's value to it. I added a note for context explaining the purpose and that if you use this to check conditions, it will only work for HTTP requests, not _all_ requests such as internal `graphql()` calls.

**Pull request merged**
