### PR TITLE
Fix 1-12 regexp in phpstan.neon.dist

### PR DESCRIPTION
**Pull request by szepeviktor**
Just 1 regexp.

### CODE REVIEW

**Review by jasonbahl — APPROVED** [review]
Thanks! 🙏

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by szepeviktor** [comment]
@jasonbahl Have you seen the research result on main file parts?
https://github.com/szepeviktor/small-project/blob/master/MAIN-FILE-PARTS.md
dubbed _How to leave legacy technologies behind_ https://twitter.com/szepeviktor/status/1361593455592488964

**Comment by jasonbahl** [comment]
@szepeviktor I've not seen that. Thanks for sharing. Will check it out 👀

**Pull request merged**
