### PR TITLE
release: v1.29.1

### PR DESCRIPTION
**Pull request by jasonbahl**
### Chores / Bugfixes

- [#3226](https://github.com/wp-graphql/wp-graphql/pull/3226): chore: add blueprint.json so WPGraphQL can be demo'd with a live preview on WordPress.org
- [#3218](https://github.com/wp-graphql/wp-graphql/pull/3218): docs: update upgrading.md to highlight how breaking change releases will be handled
- [#3214](https://github.com/wp-graphql/wp-graphql/pull/3214): fix: lazy-resolve Post.sourceUrl and deprecate Post.sourceUrlsBySize
- [#3224](https://github.com/wp-graphql/wp-graphql/pull/3224): chore(deps-dev): bump symfony/process from 5.4.40 to 5.4.46 in the composer group
- [#3219](https://github.com/wp-graphql/wp-graphql/pull/3219): test: add tests for querying different sizes of media items
- [#3229](https://github.com/wp-graphql/wp-graphql/pull/3229): fix: Deprecated null value warning in titleRendered callback

----

NOTE: Schema Linter Workflow "breaks" because the schema changed due to the release of WordPress 6.7 and a different default theme is now active. This is expected behavior when changing a theme. Additionally the support of new Image Types in WordPress 6.7 introduces new MimeTypeEnum values.

### CODE REVIEW

**Comment by justlevine** [comment]
> #2940: fix: Decode slug so it works with other languages

That's an old PR that was already in a previous release, no?

**Comment by justlevine** [comment]
Also, make sure to catch https://github.com/wp-graphql/wp-graphql/blob/44fa51fa54973af5ff224542027bb8e45aca6d25/readme.txt#L7 (got missed in the last release) and also the `@todo` in https://github.com/wp-graphql/wp-graphql/blob/44fa51fa54973af5ff224542027bb8e45aca6d25/readme.txt#L7

**Comment by jasonbahl** [comment]
> That's an old PR that was already in a previous release, no?

ya. . .brain fart. was prepping the release based on recently updated PRs and that snuck in as I was writing the changelog. (aka the case for changesets)

**Comment by justlevine** [comment]
> (aka the case for changesets)

(better known as the case for version bumping on `develop` to _push_ to `main` in lieu of a release CI 😜)

**Comment by jasonbahl** [comment]
@justlevine ugh, and now a case of the "tests run fine locally, but fail in Githubs"

CleanShot 2024-11-07 at 20 16 44@2x

🤦🏻‍♂️

**Comment by jasonbahl** [comment]
Tests were passing local but not in Github due to cdn blocking the image when requested from GitHub. I moved the image to GitHub so that GitHub can test the image from itself instead of a remote origin.

**Pull request merged**
