### PR TITLE
fix(resolver): check if `name` is an array

### PR DESCRIPTION
**Pull request by BronsonQuick**
What does this implement/fix? Explain your changes.
---------------------------------------------------

This is a fairly big edge case but we're using WPGraphQL with Next.js. Our application replaces a bunch of different CMS and as a result there are backlinks from other sites to legacy URLs. Most of those result in successful 404's which we can handle on the frontend however we noticed one edge case with an old URL which has the following URL pattern:

`/api/getServices?name[]=<slug>`

Essentially any request that has `?name=[]` will end up hitting this issue.

Currently this causes an error for us and we'd prefer if it just returned a `null` value for the page without an Internal server error.

Does this close any currently open issues?
------------------------------------------

No. 

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------

Before:

before

After:

after

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Operating System:**
* Ubuntu Jammy Jellyfish

**WordPress Version:**

* 6.1.1

### CODE REVIEW

**Comment by jasonbahl** [comment]
@BronsonQuick would you be interested in writing a test case for this so we can ensure we don't cause a regression in the future?

**Comment by BronsonQuick** [comment]
@jasonbahl Sure thing. I'll try and carve out some time on the weekend for that seeing I don't have unit tests setup for it yet.

**Comment by jasonbahl** [comment]
@BronsonQuick sweet! let me know if you need any help or whatever. I think the docs for running tests are updated, but if you have trouble you should be able to follow the steps in the github testing workflow to get tests running in Docker.

**Comment by BronsonQuick** [comment]
@jasonbahl Sorry for the delay on adding a test. I was busy last week. I've had a crack at adding a test for this. Let me know if that's what you were after!

**Comment by justlevine** [comment]
Hey @BronsonQuick , would you mind testing if the `resolve_uri()` refactor solves this as well, or if we need to retool it to incorporate this edge case?

The test you wrote is passing, but since im not 100% your setup I want to confirm.

**Comment by BronsonQuick** [comment]
Hey @justlevine, I just pulled down https://github.com/wp-graphql/wp-graphql/pull/2680 and I can confirm that I'm getting the `null` value that I am expecting that that PR. So I'm happy to close this one out seeing it's handle there. Thanks!

**Pull request closed without merging**
