### PR TITLE
♿️ Feature: docs accessibility enhancements

### PR DESCRIPTION
**Pull request by jacobarriola**
- [x] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *our develop*.
- [x] Make sure you are requesting to pull request from a **topic/feature/bugfix branch** (right side). Don't pull request from your master!

What does this implement/fix? Explain your changes.
---------------------------------------------------
See comment on issue that details items that are addressed: https://github.com/wp-graphql/wp-graphql/issues/1049#issuecomment-576101965

Does this close any currently open issues?
------------------------------------------
#1049 

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
n/a

Any other comments?
-------------------
On the UI, I made links underline since the darker blue made it harder for them to stand out.

### CODE REVIEW

**Comment by jasonbahl** [comment]
@jacobarriola Thanks SO MUCH for working on this! 

It looks like Netlify is failing to build this with the following error:

`Can't resolve '../../components/SEO/index' in '/opt/build/repo/docs/src/gatsby-theme-apollo-docs/components'`

**Comment by jacobarriola** [comment]
@jasonbahl ok. I'll review tonight.

**Comment by jacobarriola** [comment]
@jasonbahl all fixed! Silly typo 🤦‍♂ . Sorry about that 💯

**Comment by jasonbahl** [comment]
Thanks!

**Pull request merged**
