### PR TITLE
Feature/#1045 expose post types and taxonomies at root

### LINKED ISSUE #1045: Make all Nodes available via root query fields (PostTypes and Taxonomies)
This will be helpful for Gatsby integrating with WPGQL because I'm pulling all root fields that are lists of nodes, and creating Gatsby nodes out of them. Then any time a connection field is connected to a node I've fetched I just get the id and link it in Gatsby to reduce the amount of fetching that needs to happen. Currently there are PostTypes and Taxonomies nodes but no root field to get a list of them.

### PR DESCRIPTION
**Pull request by jasonbahl**
What does this implement/fix? Explain your changes.
---------------------------------------------------
- **BREAKING**: replace PostTypeEnum with ContentTypeEnum (and update all references)
- Register connections from RootQuery->ContentType and a oneToOne connection from each PostTypeObject to it's ContentType
- **BREAKING**: remove `postTypeInfo` field from connections to PostTypeObjects. Each PostTypeObject node now has a `contentType` field to access the ContentType node it's associated with
- Register connections from RootQuery->Taxonomy and a oneToOne connection from each TermNode to it's Taxonomy
- **BREAKING**: remove taxonomyInfo from taxonomy connections. Each TermNode now has a taxonomy field to access the Taxonomy node it's associated with. The shape of the `taxonomy` field is now different as well.
- Change the global ID for ContentType to use `contentType` instead of `postType`
- Add ContentTypeConnectionResolver for resolving connections to ContentType nodes
- Add TaxonomyConnectionResolver for resolving connections to Taxonomy nodes
- Add initial work for registering oneToOne connections. Used by TermNode->Taxonomy and PostObject->ContentType connections. Will be flushed out more in a PR for #347
- Add ContentTypeIdEnum and TaxonomyIdTypeEnum
- Add RootQuery.contentType and RootQuery.taxonomy fields to query ContentType nodes and Taxonomy nodes by ID, and supports the idType argument to use multiple types of identifiers (ID and Name, currently)
- Update tests to reflect changes to queries for the `category.taxonomy` and `tag.taxonomy` field
- Update tests to reflect changes to access ContentType and Taxonomy info on connections

Does this close any currently open issues?
------------------------------------------
closes #1045 

Any other comments?
-------------------
Here are some examples of before/after queries: 

## Query TaxonomyInfo (Before)

```
{
  tags {
    taxonomyInfo { #This returns a Taxonomy node, similar to calling get_taxonomy( 'post_tag' )
       id
       name
    }
    nodes {
       id
       name
       taxonomy { #This returns a Taxonomy type, similar to calling get_taxonomy( 'post_tag' )
         name
       }
    }
  }
}
```

Screen Shot 2020-01-29 at 9 27 03 AM

## Query TaxonomyInfo (After)

```
{
  tags {
      nodes {
         id
         name
         taxonomy { # This now returns a oneToOne connection to a Taxonomy node
            
            # Note this edge space between taxonomy and node. 
            # Contextual info about the connection between the Tag node and the Taxonomy 
            # it belongs to (should there ever be any) can be added here.
            
            node { #This returns a Taxonomy node, similar to calling get_taxonomy( 'post_tag' )
               id
               name
            }
         }
      }
   }
}
```

Screen Shot 2020-01-29 at 9 19 10 AM

## Query PostTypeInfo (before)

```
{
  posts {
     postTypeInfo { # This returned a PostType type, similar to calling get_post_type_object( 'post' );
        name
     }
     nodes {
         id
         title
         # Note: there is no field to query for postType or contentType from a Post object node
      }
  }
}
```

Screen Shot 2020-01-29 at 9 27 33 AM

## Query PostTypeInfo (after)

```
{
  posts {
     nodes {
         id
         title
         contentType {

            # Note this edge space between contentType and node. 
            # Contextual info about the connection between the Post node and the ContentType node 
            # it belongs to (should there ever be any) can be added here.
            
            node { # This returns a ContentType node, similar to calling get_post_type_object( 'post' );
                name
            }
         }
      }
  }
}
```
Screen Shot 2020-01-29 at 9 18 36 AM

## Query All ContentTypes (Post Types)

This RootQuery->ContentType connection allows for Content Types (post types) to be queried from the root. All properties of the ContentType can be asked for, such as labels, etc. 

```
{
  contentTypes {
     nodes {
        id
        name
        graphqlSingleName
        graphqlPluralName
     }
  }
}
```

Screen Shot 2020-01-29 at 9 16 57 AM

## Query Single Taxonomy Node by ID

```
{
  taxonomy(id: "dGF4b25vbXk6cG9zdF90YWc=") {
    id
    name
    graphqlSingleName
    graphqlPluralName
  }
}
```

Screen Shot 2020-01-29 at 9 22 39 AM

## Query Single Taxonomy Node by Name

```
{
  taxonomy(id: "post_tag" idType: NAME ) {
    id
    name
    graphqlSingleName
    graphqlPluralName
  }
}
```

Screen Shot 2020-01-29 at 9 22 16 AM

## Query Single ContentType (Post Type) by ID

```
{
  contentType( id: "" ) {
    id
    name
    graphqlSingleName
    graphqlPluralName
  }
}
```

Screen Shot 2020-01-29 at 9 24 30 AM

## Query Single ContentType (Post Type) by Name

```
{
  contentType( id: "post", idType: NAME ) {
    id
    name
    graphqlSingleName
    graphqlPluralName
  }
}
```

Screen Shot 2020-01-29 at 9 24 01 AM

### CODE REVIEW

**Comment by TylerBarnes** [comment]
This is looking awesome! 🎉 
It will be nice to be able to get post type data on a ContentNode or on an individual post. One thing I'm not sure about is if it makes sense to remove postTypeInfo from a list of posts. It still seems useful to pull that once instead of on each individual node to reduce the amount of data that needs to be fetched.
A consumer could pull `posts { ... fields }` and
```graphql
{
  contentType( id: "post", idType: NAME ) {
    id
    name
    graphqlSingleName
    graphqlPluralName
  }
}
```
In one query though 🤔 so maybe it's fine to remove `postTypeInfo`

**Comment by jasonbahl** [comment]
> It will be nice to be able to get post type data on a ContentNode or on an individual post. One thing I'm not sure about is if it makes sense to remove postTypeInfo from a list of posts. It still seems useful to pull that once instead of on each individual node to reduce the amount of data that needs to be fetched.

@TylerBarnes ya, that was my initial thought when I added it, but in practical terms I couldn't justify why it needs to be there. 

I was thinking, oh, I'm going to query a list of Posts, and if I get the PostTypeInfo once, I can just use that, but tools like Apollo cache the connection from the Post->ContentType, and not the Post->someRandomFieldOnTheConnection

You'd have to go out of your way to associate each Post node with the PostTypeInfo if it's delivered from the Connection

I'm open to adding it back if there's a compelling use case for it that I'm missing. 

I suppose it might not hurt anything to have it exposed there, but it also seems like it's not serving the purpose I originally thought it would.

**Comment by TylerBarnes** [comment]
No, you're right, it makes sense to remove it!

**Comment by jasonbahl** [comment]
@TylerBarnes cool. Let me know if you run into any issues. You're REALLY good at catching the edge cases 😆

**Comment by michaellopez** [comment]
Awesome work 😍

**Pull request merged**
