### PR TITLE
ci: Implement `WPGraphQL-Strict` PHPCS ruleset

### PR DESCRIPTION
**Pull request by justlevine**
What does this implement/fix? Explain your changes.
---------------------------------------------------
The following PR _shows the implications_ of the [`WPGraphQL-Strict`](https://github.com/AxeWP/WPGraphQL-Coding-Standards) ruleset. **It is not meant to be merged**.

This ruleset restores currently-excluded sniffs from our existing PHPCS ruleset, as well as adds:
- Additional _functional_ sniffs from the Slevomat-Coding-Standards library. These sniffs relate primarily to performance, modern code practices, and can mostly be addressed automatically by running `phpcbf` (see the commit diff: https://github.com/wp-graphql/wp-graphql/commit/769525975116f8917d93df8b5600f94d7f9099f1).
- The (imo) bare minimum of annotation sniffs: all methods must have a doc-block, all params must be listed, and `sprintf()` interpolation requires a `translators` comment.

**Note:** 
- Some sniffs are disabled due to the breaking changes required to implement them (e.g. `snake_case` method names).
- Not _all_ smells are addressed in this PR. There are a few `unused variable` smells that need a decision to resolve, and I didnt address in missing annotation smells (~e.g. translator comments~ #2856 ), since the remediation of those sniffs are obvious and not worth the effort in a PR that isnt meant to be merged.

Once feedback on the proposed ruleset is gathered and approved by @jasonbahl , this PR will be _closed_, and a new one (or several) will be created to implement them in our codebase (e.g. #2855).

### How to review

[Leave a comment](https://github.com/wp-graphql/wp-graphql/pull/2830/files) on any change you disagree with (one comment per 'type' of change - i.e. sniff is enough, there are over 1500+ individual smells addressed).

Does this close any currently open issues?
------------------------------------------
No.

Any other comments?
-------------------
1. The proposal is **not** to replace our existing PHPCS-related dependencies with `axepress/wp-graphql-cs`, that's just being used to centralize the proposed changes across multiple codebases.

Where has this been tested?
---------------------------
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + php 8.0.26)

**WordPress Version:** 6.2.2

### CODE REVIEW

**Comment by jasonbahl** [comment]
@justlevine I believe parts of this were merged in #2855 and #2856?

**Comment by justlevine** [comment]
@jasonbahl static callbacks (autofixed so in this diff) and translation comments (not in the diff).

If it will make it easier for you to review I'm happy to rebase, but probably the most effective way to review this would be to update the composer.json and phpcs.xml on a local branch of develop, and then:

1. Run `composer fix-cs` and compare the diff to see what if any changes you disagree with. (As autofixable, the criteria for inclusion I'm assuming are lower).

2. Run `composer phpcs` and see what reported sniffs you disagree with (as these require manual resolution, there should be extra consideration about if they provide a barrier to entry to new contributors / unnecessary work for maintainers).

Let me know if I should force-push a rebase :)

**Comment by justlevine** [comment]
For reference on ecosystem impact see the diffs in:
- https://github.com/AxeWP/wp-graphql-plugin-boilerplate/pull/7
- https://github.com/AxeWP/wp-graphql-headless-login/pull/80
- https://github.com/AxeWP/wp-graphql-gravity-forms/pull/369
- https://github.com/hsimah-services/wp-graphql-facetwp/pull/62
- https://github.com/AxeWP/wp-graphql-rank-math/pull/51
- https://github.com/wp-graphql/wp-graphql-woocommerce/pull/769 (as well as the prs linked to it)
- https://github.com/wpengine/wp-graphql-content-blocks/pull/126 (other items were merged in separately for 1.0, but I didn't write a list)

**Comment by jasonbahl** [comment]
@justlevine ya, I suppose push a rebase 🤔

**Comment by justlevine** [comment]
@jasonbahl just pushed the rebase.

- https://github.com/wp-graphql/wp-graphql/pull/2830/commits/74025b8b24fa141f1f5b1021ffe7a31cb01f8d61 Is the diff of the autofixes.
- https://github.com/wp-graphql/wp-graphql/pull/2830/commits/0def6de11ba29737fafc46f588e62b389c99009d Is the diff for issues that had to be manually resolved.

Recommend way to review is to scroll those diffs and comment when you see something you dont like (its a ruleset so no need to recomment on repeat occurrences).

There are currently 3 sniffs unresolved. Each of them are an unused variable where it's unclear (to me at least) whether they're tech debt that can be removed or bugs and they _should_ be used. (Would love you feedback to address them _regardless_ of whether this proposed ruleset gets approved, but it does underscore the value these extra sniffs add):

image

**Review by jasonbahl — APPROVED** [review]

**Comment by justlevine** [comment]
All included changes have been cherrypicked into the following individual PRs:
- #2898
- #2899
- #2900
- #2901
- #2902

Closing.

**Pull request closed without merging**
