### PR TITLE
fix: update `appsero/client` to v2.0.4 to prevent conflicts with WP6.7

### LINKED ISSUE #3239: WordPress 6.7 changes in translation throw a warning when WP_DEBUG is on
### Description

After upgrading WordPress to version 6.7 and enabling `WP_DEBUG`, the following error/warning can be observed in the admin pages (at the very top, right under toolbar). This error/warning also shows up in the frontend.

```
Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the wp-graphql domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see Debugging in WordPress for more information. (This message was added in version 6.7.0.) in wp-includes/functions.php on line 6114
```

### Steps to reproduce

- install WordPress version 6.7 or higher
- install WPGraphQL plugin, latest version (1.29.2 at the time of writing)
- set `WP_DEBUG` to `true` in `wp-config.php`
- observe the error/warning as described earlier

### Additional context

No other plugins are running. Theme is `Twenty Twenty-Four`.

### WPGraphQL Version

1.29.2

### WordPress Version

6.7.1

### PHP Version

8.3.12

### Additional environment details

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

### PR DESCRIPTION
**Pull request by justlevine**
What does this implement/fix? Explain your changes.
---------------------------------------------------
This PR updates `appsero/client` to v2.0.4, which [contains the compatibility fix for WP 6.7](https://github.com/Appsero/client/releases/tag/v2.0.4)

To prevent 3rd party conflicts (and a repeat of https://github.com/wp-graphql/wp-graphql/pull/2599), use of `Appsero\Client` has been wrapped in a try/catch block. 

> [!IMPORTANT]
> This PR is based on #3242 which should be merged first.

Does this close any currently open issues?
------------------------------------------

Fixes #3239 

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------

Any other comments?
-------------------
Alternatively tried namespacing the dependency (which is the code-ideal solution), however Strauss is not compatible with PHP 7.3 (what Composer uses to compile on).

Where has this been tested?
---------------------------
**Operating System:** Ubuntu 24.04 (WSL + ddev + PHP 8.2.24 )

**WordPress Version:** 6.7.1

### CODE REVIEW

**Review by jasonbahl — APPROVED** [review]

**Review by jasonbahl — APPROVED** [review]

**Comment by Messa1** [comment]
@justlevine I got some error on updating over composer

wp-graphql-smart-cach
wp-graphql/wp-graphql-smart-cache

Mabye, also need some composer update?

I can't install the new wp-graphql/wp-graphql version.

**Comment by justlevine** [comment]
@Messa1 can you be more specific about what "over composer" means? Are you using WPackagist or something else?

**Comment by Messa1** [comment]
@justlevine 

https://github.com/wp-graphql/wp-graphql-smart-cache/blob/5ffd6f59538800342ec2257754b7d9e5d8638c9e/composer.json#L41

https://github.com/wp-graphql/wpgraphql-acf/blob/ef88bd167a7b29489aa56027635f07385b6be443/composer.json#L14

composer.json
```
  "require": {
    "php": ">=8.0",
    "composer/installers": "^2.2",
    "vlucas/phpdotenv": "^5.5",
    "oscarotero/env": "^2.1",
    "roots/bedrock-autoloader": "^1.0",
    "roots/bedrock-disallow-indexing": "^2.0",
    "roots/wordpress": "6.6.2",
    "roots/wp-config": "1.0.0",
    "roots/wp-password-bcrypt": "1.1.0",
    "wpackagist-theme/twentytwentyfour": "^1.0",
    "wpengine/advanced-custom-fields-pro": "^6.3",
    "wpengine/wp-graphql-content-blocks": "dev-main",
    "wp-graphql/wp-graphql": "^1.29",
    "wp-graphql/wpgraphql-acf": "^2.4",
    "wp-graphql/wp-graphql-smart-cache": "^1.3.3",
    }
```

**Comment by justlevine** [comment]
Yup as expected, you're installing the source (from `wp-graphql/wp-graphql` instead of using [WPackagist](https://www.wpgraphql.com/docs/quick-start#install-with-composer), so Composer is trying to rebuild the dependencies instead of using those shipped in the plugins.

(Iirc smart-cache is on .org too so you might want to use `wpackagist-plugin/wp-graphql-smart-cache` too)

**Comment by jasonbahl** [comment]
@Messa1 it's `wpgraphql-smart-cache`

see: https://wpackagist.org/search?q=wpgraphql-smart-cache&type=any&search=

At some point WordPress.org stopped allowing plugins that started with `wp-` so we had to go with `wpgraphql` without the first `-` when we released WPGraphQL Smart Cache.

**Pull request merged**
