### PR TITLE
#1029 follow up

### PR DESCRIPTION
**Pull request by jasonbahl**
Follow-up to #1029 

@CodeProKid @zgordon This is a follow up to #1029 

I'm having some funky git issues locally I think. I couldn't pull Zac's branch, but now I'm having other strange issues. 

Anyway, this addresses the formatting suggestions from @CodeProKid and fixes the edge case @zgordon was running into

### CODE REVIEW

**Comment by CodeProKid** [comment]
Looking good, should probably get some tests on this too, eh? 😉

**Comment by jasonbahl** [comment]
@CodeProKid writing them as we type

**Comment by CodeProKid** [comment]
https://media.giphy.com/media/rMS1sUPhv95f2/giphy.gif

**Comment by CodeProKid** [comment]
hacking

**Comment by jasonbahl** [comment]
@CodeProKid initial test added

**Pull request merged**
