### PR TITLE
perf: refactor `PluginConnectionResolver` to only fetch plugins once

### PR DESCRIPTION
**Pull request by justlevine**
What does this implement/fix? Explain your changes.
---------------------------------------------------
This PR refactors our `PluginConnectionResolver` class to use a DRY `::get_all_plugins()` method for building the list of available plugins.
This list is then stored in a class property, so the fetching, filtering, etc only occur once.

Does this close any currently open issues?
------------------------------------------

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------

Part of #2749

Any other comments?
-------------------
This PR is based on #3082 , which should be merged first.

Where has this been tested?
---------------------------
**Operating System:** Ubuntu 20.04 (wsl2 + devilbox + php 8.1.15)

**WordPress Version:** 6.4.3

### CODE REVIEW

**Review by jasonbahl — APPROVED** [review]

**Comment by justlevine** [comment]
Ps @jasonbahl it might be easier for you to review/merge #3082 _first_, (PRs based on it, should auto-update the branch to `develop`).

From my side: I don't know your availability for reviewing them all, but merging the parent PRs before the dependents would also let me continue backporting more things while decreasing the risk of merge conflicts.

**Comment by jasonbahl** [comment]
This one didn't look like it had any direct connection to the others and could be merged as-is. 

The others did seem to have a lot more correlation.

**Comment by justlevine** [comment]
@jasonbahl this was merged into #3082 , not into #3097 . We probably should amend the release notes.

**Comment by jasonbahl** [comment]
@justlevine ooph. Good call. Will update. Thanks. Just got the test results back and this was another case of the "moving too fasts"

**Comment by jasonbahl** [comment]
@justlevine edited the release notes: https://github.com/wp-graphql/wp-graphql/releases/tag/v1.23.0

**Pull request merged**
