### PR TITLE
fix: GraphiQL Query Composer update to FieldView for union type

### PR DESCRIPTION
**Pull request by chrisherold**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Discussed in #2287, Flexible Content and Relationship fields that are Union types don't have sub fields but rather sub types. There's existing code in the Query Composer FieldView component for Union types but that only gets executed in the context of sub fields https://github.com/wp-graphql/wp-graphql/blob/develop/packages/graphiql-query-composer/components/FieldView.js#L402. Adding that logic as an `else if` after the `if` statement for sub fields resolves the issue and correctly displays the Union type fields.

There appears to be a typo in `_addAllFieldsToSelections` where the function arg camel casing doesn't match the references in the function. Updated both cases to avoid confusion.

Also, made one small change to the packages/readme as I had to run `npm run start` as opposed `npm run dev` to get the GraphiQL app running in dev mode

Does this close any currently open issues?
------------------------------------------
#2287, #2370, wp-graphql/wp-graphql-acf#312, wp-graphql/wp-graphql-acf#319

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Operating System:** MacOS Monterey 12.6

**WordPress Version:** 5.9.3

### CODE REVIEW

**Comment by jasonbahl** [comment]
@chrisherold checking this out now. 👀 Thanks so much!

**Comment by jasonbahl** [comment]
@chrisherold just pulled this and tested it with ACF and with the (deprecated) `MenuItem.connectedObject` union field, and it's working great!

Very much appreciate you taking the time to work through this. I know it will help a lot of users! 👏🏻

**Comment by jasonbahl** [comment]
for the record, here's a before/after:

## Before

There's no sub-selection for `flexFieldGroup` field. There _should_ be the different Types available for the Union.

CleanShot 2022-10-07 at 14 33 23



## After

The possible types for the union are visible and selectable, as expected:

CleanShot 2022-10-07 at 14 33 01

**Comment by jasonbahl** [comment]
@chrisherold this will go out with 1.12.0 on Monday! 👏🏻 

Again, thanks so much for your work on this! Many people will appreciate this fix!

**Comment by chrisherold** [comment]
Awesome, glad to be able to contribute

**Pull request merged**
